SELECT TABLE_NAME as 'nom de la table', GROUP_CONCAT(COLUMN_NAME) as 'Clé primaire'
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE
  TABLE_SCHEMA = 'biblio'
  AND CONSTRAINT_NAME='PRIMARY'
GROUP BY TABLE_NAME;